### ISSUE TITLE
Problem while authenticating user with mongodb using morphium

### ISSUE THREAD

**Issue by KiranNaikwade** [sboesebeck/morphium#17]
When i am trying to authenticate user with mongodb using morphium. But i am getting below error even though the credentials are correct. And also some problem with thread termination.

Code sample:

	private static Morphium getMorphium() throws UnknownHostException {
		Morphium morphium = null;
		MorphiumConfig cfg = new MorphiumConfig();
		cfg.addHostToSeed("xx.xx.x.xxx:27017");
		cfg.setDatabase("testdb");
		cfg.setMongoLogin("testuser");
		cfg.setMongoPassword("testpass");
		MorphiumSingleton.setConfig(cfg); // Create a singleton object
		morphium = MorphiumSingleton.get();
		System.out.println("Connected with database....");
		return morphium;
	}

Error : 

com.mongodb.MongoSecurityException: Exception authenticating
	at com.mongodb.connection.NativeAuthenticator.authenticate(NativeAuthenticator.java:48)
	at com.mongodb.connection.InternalStreamConnectionInitializer.authenticateAll(InternalStreamConnectionInitializer.java:99)
	at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:44)
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:115)
	at com.mongodb.connection.UsageTrackingInternalConnection.open(UsageTrackingInternalConnection.java:46)
	at com.mongodb.connection.DefaultConnectionPool$UsageTrackingInternalConnectionItemFactory.create(DefaultConnectionPool.java:487)
	at com.mongodb.connection.DefaultConnectionPool$UsageTrackingInternalConnectionItemFactory.create(DefaultConnectionPool.java:475)
	at com.mongodb.internal.connection.ConcurrentPool.createNewAndReleasePermitIfFailure(ConcurrentPool.java:164)
	at com.mongodb.internal.connection.ConcurrentPool.ensureMinSize(ConcurrentPool.java:158)
	at com.mongodb.connection.DefaultConnectionPool$3.run(DefaultConnectionPool.java:298)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.mongodb.MongoCommandException: Command failed with error 18: 'auth failed' on server xx.xx.x.xxx:27017. The full response is { "ok" : 0.0, "errmsg" : "auth failed", "code" : 18 }
	at com.mongodb.connection.CommandHelper.createCommandFailureException(CommandHelper.java:170)
	at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:123)
	at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32)
	at com.mongodb.connection.NativeAuthenticator.authenticate(NativeAuthenticator.java:46)
	... 16 more

Note :  If i try to do authentication using below code. It will work fine.

	private static Morphium getMorphiumFromJson() throws Exception {
		Morphium morphium = null;
		String json = "{ \"hosts\":\"xx.xx.x.xxx:27017\", \"database\" : \"testdb\", \"mongoLogin\" : \"testuser\", \"mongoPassword\" : \"testpass\",\"write_timeout\" : 9990 }";
		MorphiumConfig cfg = MorphiumConfig.createFromJson(json);
		MorphiumSingleton.setConfig(cfg); // Create a singleton object
		morphium = MorphiumSingleton.get();
		System.out.println("Connected with database....");
		return morphium;
	}

Issue seen in  :
Morphium :   ALPHA Release 3.0
mongo-java-driver : 3.2

**Comment by sboesebeck** [comment]
Which version of morphium/mongodb are you using?

**Comment by KiranNaikwade** [comment]
I am using : 
Morphium ALPHA Release 3.0
mongodb : 3.2

**Comment by sboesebeck** [comment]
The authentication is pretty much untested in 3.0.0ALPH... 

which driver are you using? The default driver or did you change it?

**Comment by sboesebeck** [comment]
fixed... already available in develop, will be part of ALPHA2

**Comment by KiranNaikwade** [comment]
Thanks for your support. . .

I am getting one more problem while authenticating using JSON.

Sample code : 

	private static void getMorphiumFromJson() throws Exception {
		Morphium morphium = null;
		String json = "{ \"hosts\":\"xx.xx.x.xxx:27017\", \"database\" : \"testdb\", \"mongoLogin\" : \"testuser\", \"mongoPassword\" : \"testpass\",\"write_timeout\" : 9990 }";
		MorphiumConfig cfg = MorphiumConfig.createFromJson(json);
		MorphiumSingleton.setConfig(cfg); // Create a singleton object
		morphium = MorphiumSingleton.get();
		System.out.println("Connected with database....");
		Registration registration = new Registration();
		morphium.store(registration);
		System.out.println("User registered successfully...");
	}

Error : 

Exception in thread "main" java.lang.RuntimeException: de.caluga.morphium.driver.MorphiumDriverException: internal error
	at de.caluga.morphium.writer.MorphiumWriterImpl$1.run(MorphiumWriterImpl.java:221)
	at de.caluga.morphium.writer.MorphiumWriterImpl.submitAndBlockIfNecessary(MorphiumWriterImpl.java:743)
	at de.caluga.morphium.writer.MorphiumWriterImpl.store(MorphiumWriterImpl.java:227)
	at de.caluga.morphium.Morphium.store(Morphium.java:1929)
	at de.caluga.morphium.Morphium.store(Morphium.java:1919)
	at de.caluga.morphium.Morphium.store(Morphium.java:1910)
	at com.quickheal.cloud.factory.QHMorphiumDaoManager.getMorphiumFromJson(QHMorphiumDaoManager.java:52)
	at com.quickheal.cloud.factory.QHMorphiumDaoManager.getInstance(QHMorphiumDaoManager.java:35)
	at com.quickheal.cloud.factory.Main.main(Main.java:21)
Caused by: de.caluga.morphium.driver.MorphiumDriverException: internal error
	at de.caluga.morphium.driver.mongodb.DriverHelper.handleNetworkError(DriverHelper.java:75)
	at de.caluga.morphium.driver.mongodb.DriverHelper.doCall(DriverHelper.java:31)
	at de.caluga.morphium.driver.mongodb.Driver.exists(Driver.java:870)
	at de.caluga.morphium.writer.MorphiumWriterImpl$1.run(MorphiumWriterImpl.java:129)
	... 8 more
Caused by: com.mongodb.MongoCommandException: Command failed with error 13: 'not authorized on andrcloud to execute command { listCollections: 1 }' on server 10.10.9.121:27017. The full response is { "ok" : 0.0, "errmsg" : "not authorized on andrcloud to execute command { listCollections: 1 }", "code" : 13 }
	at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:86)
	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:119)
	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:159)
	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:286)
	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:173)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:215)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:186)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:178)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:91)
	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:84)
	at com.mongodb.operation.CommandReadOperation.execute(CommandReadOperation.java:55)
	at com.mongodb.Mongo.execute(Mongo.java:773)
	at com.mongodb.Mongo$2.execute(Mongo.java:760)
	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:130)
	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:124)
	at com.mongodb.MongoDatabaseImpl.runCommand(MongoDatabaseImpl.java:114)
	at de.caluga.morphium.driver.mongodb.Driver$12.execute(Driver.java:876)
	at de.caluga.morphium.driver.mongodb.DriverHelper.doCall(DriverHelper.java:29)
	... 10 more


Note : Check some thread executors. I think you fixed it in Pre-Release V2.2.24BETA1


Thanks,
Kiran

**Comment by sboesebeck** [comment]
Hi

this is not a problem with the parsing of json, it seems like the user does not have the right to do the command listCollections Internally, this command is used to determine if a collection exists, or not. Morphium needs that in order to be able to automatically create indexes on new collections.

You can switch that off in the morphium config - setAutoIndexAndCappedCreationOnWrite

Hope that helps,,

Cheers,

Stephan

**Comment by KiranNaikwade** [comment]
Yes Stephan, You are right. User only have readWrite permission. It can not execute list collections command.

Thanks,
Kiran
