### ISSUE TITLE
time out

### ISSUE THREAD

**Issue by guoyuf** [sboesebeck/morphium#40]
Hi,

I use mophium to store large volume data to mongo and when I test I got following message, even I set the configuration as:
"maxConnections" ="100"
"socketTimeout"="600000"
"writeTimeout"="600000"

any idea on how to fix this?

thanks,
Eric
com.mongodb.MongoSocketReadTimeoutException: Timeout while receiving message
	at com.mongodb.connection.InternalStreamConnection.translateReadException(InternalStreamConnection.java:457) ~[mongodb-driver-core-3.5.0.jar:na]
	at com.mongodb.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:214) ~[mongodb-driver-core-3.5.0.jar:na]
	at com.mongodb.connection.CommandHelper.receiveReply(CommandHelper.java:134) ~[mongodb-driver-core-3.5.0.jar:na]
	at com.mongodb.connection.CommandHelper.receiveCommandResult(CommandHelper.java:121) ~[mongodb-driver-core-3.5.0.jar:na]
	at com.mongodb.connection.CommandHelper.executeCommand(CommandHelper.java:32) ~[mongodb-driver-core-3.5.0.jar:na]
	at com.mongodb.connection.InternalStreamConnectionInitializer.initializeConnectionDescription(InternalStreamConnectionInitializer.java:85) ~[mongodb-driver-core-3.5.0.jar:na]
	at com.mongodb.connection.InternalStreamConnectionInitializer.initialize(InternalStreamConnectionInitializer.java:45) ~[mongodb-driver-core-3.5.0.jar:na]
	at com.mongodb.connection.InternalStreamConnection.open(InternalStreamConnection.java:108) ~[mongodb-driver-core-3.5.0.jar:na]
	at com.mongodb.connection.DefaultServerMonitor$ServerMonitorRunnable.run(DefaultServerMonitor.java:125) ~[mongodb-driver-core-3.5.0.jar:na]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_71]
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method) ~[na:1.8.0_71]
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116) ~[na:1.8.0_71]
	at java.net.SocketInputStream.read(SocketInputStream.java:170) ~[na:1.8.0_71]
	at java.net.SocketInputStream.read(SocketInputStream.java:141) ~[na:1.8.0_71]
	at com.mongodb.connection.SocketStream.read(SocketStream.java:84) ~[mongodb-driver-core-3.5.0.jar:na]
	at com.mongodb.connection.InternalStreamConnection.receiveResponseBuffers(InternalStreamConnection.java:474) ~[mongodb-driver-core-3.5.0.jar:na]
	at com.mongodb.connection.InternalStreamConnection.receiveMessage(InternalStreamConnection.java:210) ~[mongodb-driver-core-3.5.0.jar:na]
	... 8 common frames omitted

**Comment by sboesebeck** [comment]
if you set the timeout to 0 it usually means "as long as it takes"

but this is quite strange. it is in the mongodb Driver itself. Morphium is only tested til V3.4.3 of the driver - could you try this version?

**Comment by sboesebeck** [comment]
I tried it with the new version, this error did not occur... maybe you can also set the maxWaitTime to something very high?

**Comment by sboesebeck** [comment]
have it running here in several projects, cannot reproduce the error!
