### ISSUE TITLE
Versioning implementation using morphium.store

### ISSUE THREAD

**Issue by arwa123** [sboesebeck/morphium#47]
I am trying to implement versioning for one one of my model class.
I am using morphium.store() for updating the data and getting the below error -
Version mismach - write failed  caused by : E11000 duplicate key error java.
tag - v.4.0.7

**Comment by sboesebeck** [comment]
could you please provide more information. Can you reproduce that with an empty collection?
do you get an exception and maybe a stacktrace?

**Comment by arwa123** [comment]
This is the code to test auto-versioning feature. I'm creating a dao object "roleDao" using Morphium object "m". I'm fetching Role object from DB and then updating it and saving it using morphium.store(role) in roleDao's save method.

`RoleDAO roleDao = RoleDAO.getInstance(m);

Role role = roleDao.getRoleById("5e4a60e0e6f4b92176145be7");

Role newRole = roleDao.getRoleById("5e4a60e0e6f4b92176145be7");

role.setRoleName("newData");
roleDao.save(role);

Role updatedRole = roleDao.getRoleById("5e4a60e0e6f4b92176145be7");

System.out.println("UpdatedRole is : "+ updatedRole.getRoleName() + " id: "+ updatedRole.getId()+ " version: "+ updatedRole.getVersion());
System.out.println("New Role is : "+ newRole.getRoleName() + " id: "+ newRole.getId()+ " version: "+ newRole.getVersion());
newRole.setRoleName("oldData");
roleDao.save(newRole);`

This is the save method in RoleDAO:

`public void save(Role role){
    System.out.println("Role: "+ role.toString() + " is being saved.....");
    morphium.store(role);
    System.out.println("Role : "+ role.toString() + " has been saved.....");
}`

Running this, I get an exception:

StackTrace:
2655 [main] INFO de.caluga.morphium.driver.mongodb.DriverHelper - Handling network error...java.util.ConcurrentModificationException
Exception in thread "main" java.lang.RuntimeException: de.caluga.morphium.driver.MorphiumDriverException: internal error: Version mismach - write failed
	at de.caluga.morphium.writer.MorphiumWriterImpl$6.run(MorphiumWriterImpl.java:528)
	at de.caluga.morphium.writer.MorphiumWriterImpl.submitAndBlockIfNecessary(MorphiumWriterImpl.java:1048)
	at de.caluga.morphium.writer.MorphiumWriterImpl.store(MorphiumWriterImpl.java:534)
	at de.caluga.morphium.Morphium.store(Morphium.java:2297)
	at de.caluga.morphium.Morphium.store(Morphium.java:2284)
	at de.caluga.morphium.Morphium.store(Morphium.java:2272)
	at dao.RoleDAO.save(RoleDAO.java:71)
	at Main.Main.updateRoleNameTest(Main.java:75)
	at Main.Main.main(Main.java:56)
Caused by: de.caluga.morphium.driver.MorphiumDriverException: internal error: Version mismach - write failed
	at de.caluga.morphium.driver.mongodb.DriverHelper.handleNetworkError(DriverHelper.java:86)
	at de.caluga.morphium.driver.mongodb.DriverHelper.doCall(DriverHelper.java:41)
	at de.caluga.morphium.driver.mongodb.Driver.store(Driver.java:1064)
	at de.caluga.morphium.writer.MorphiumWriterImpl$6.run(MorphiumWriterImpl.java:486)
	... 8 more
Caused by: java.util.ConcurrentModificationException: Version mismach - write failed
	at de.caluga.morphium.driver.mongodb.Driver.lambda$store$12(Driver.java:1116)
	at de.caluga.morphium.driver.mongodb.DriverHelper.doCall(DriverHelper.java:28)
	... 10 more

PS : When I use set, instead of store, to modify particular fields, it works fine.

**Comment by sboesebeck** [comment]
Thanks a lot, I can reproduce the bug... hope to be able to provide a fix asap.

Cation: When using SET the version cannot be checked. Set is just calling $set in MongoDB.

**Comment by sboesebeck** [comment]
I implemented a fix (and a test) for this in current dev... can you try that version?

**Comment by arwa123** [comment]
Thank you so much . Can you create a new tag for this change so that i can test it out ?

**Comment by sboesebeck** [comment]
just tagged it with 'versioning_fix_candidate'

**Comment by arwa123** [comment]
I am using maven dependency of morphium in my project in pom.xml. How should I use this tag to test since it is not in maven repo.

**Comment by sboesebeck** [comment]
you'd need to install morphium-dev locally. Check out the develop branch and run `mvn -DskipTests install` in the directory. this installs 4.2.1-SNAPSHOT to your local machine... 

We cannot upload snapshots yet.

**Comment by arwa123** [comment]
Thanks a lot. Fix is woring fine. When can we expect this fix to be released.

**Comment by sboesebeck** [comment]
Well, the new "encryped field" feature needs to be at least in a beta stage. We try to have a pre release out by next week... if all works fine, no additional bugs are found, we could have the final release out in March.
